version: '3'

services:
  mysql:
    container_name: "maria_db"
    image: "mariadb:latest"
    environment:
      MYSQL_DATABASE: Db
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"
  
  java:
    container_name: "wildfly_server"
    build: ./java
    volumes:
      - ./java/target:/opt/jboss/wildfly/standalone/deployments/
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - mysql

networks:
  default:
    driver: bridge